version: '3'

services:
    nginx:
        image: nginx:1.18
        volumes:
            - ./conf/nginx/conf.d:/etc/nginx/conf.d
            - /tmp:/tmp
    haproxy:
        image: haproxy:1.8
        volumes:
            - ./conf/haproxy:/usr/local/etc/haproxy
            - /tmp:/tmp
        ports:
            - 8443:443
    v2ray:
        image: v2fly/v2fly-core:v4.24.2
        volumes:
            - ./conf/v2ray:/etc/v2ray
            - /tmp:/tmp